name: CI/CD Frontend

on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main
      - production

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar pnpm
        run: npm install -g pnpm

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build
        run: pnpm run build
